# Fits censored exponential interarrival models using an equivalent Poisson likelihood.
# Produces clustered coefficient estimates, average post-fight effects, and model summaries.

fit_IAT_log_model <- function(
    working.dir,
    pbp_master_used,
    min_before = 1,
    min_after = 1
) {
  
  # 1. Identify the season range
  seasons_used <- pbp_master_used %>%
    distinct(season) %>%
    filter(!is.na(season)) %>%
    pull(season) %>%
    as.character()
  
  if (length(seasons_used) == 0) {
    stop("pbp_master_used contains no valid seasons.")
  }
  
  season_numbers <- as.numeric(seasons_used)
  
  if (any(is.na(season_numbers))) {
    stop("At least one season could not be converted to numeric.")
  }
  
  first_season <- min(season_numbers)
  last_season <- max(season_numbers)
  season_folder_name <- paste0(first_season, "_", last_season)
  
  message("Working on season range: ", season_folder_name)
  
  # 2. Load and validate the interarrival dataset
  data_raw <- readRDS(
    file.path(
      working.dir,
      "generated",
      "fights",
      "single_fight_games_IAT_table.rds"
    )
  )
  
  if (!"pre_fight_window" %in% names(data_raw)) {
    stop(
      "single_fight_games_IAT_table.rds has no pre_fight_window column. ",
      "Rerun build_all_IAT_tables() to rebuild it with the pre-fight ",
      "window indicator."
    )
  }
  
  if (!"season_month" %in% names(data_raw)) {
    stop(
      "single_fight_games_IAT_table.rds has no season_month column. ",
      "Rerun build_all_IAT_tables() to rebuild it with month-of-season ",
      "information."
    )
  }
  
  # 3. Construct the common estimation sample
  data <- data_raw %>%
    filter(as.character(season) %in% seasons_used) %>%
    mutate(
      season = factor(season),
      fight_period = factor(fight_period, levels = c(1, 2, 3)),
      current_period = factor(current_period, levels = c(1, 2, 3)),
      season_month = factor(season_month),
      fight_score_diff_cat = factor(
        pmin(abs(as.numeric(fight_score_diff)), 3),
        levels = c(0, 1, 2, 3),
        labels = c("0", "1", "2", "3plus")
      ),
      RC = as.integer(RC),
      post_fight = as.integer(post_fight),
      pre_fight_window = as.integer(pre_fight_window),
      cluster_id = interaction(season, game_id, drop = TRUE)
    ) %>%
    filter(
      is.finite(IAT),
      IAT > 0,
      RC %in% c(0, 1),
      post_fight %in% c(0, 1),
      !is.na(season),
      !is.na(fight_period),
      !is.na(current_period),
      !is.na(pre_fight_window),
      !is.na(intradivision),
      !is.na(fight_score_diff),
      !is.na(fight_score_diff_cat),
      !is.na(cluster_id)
    ) %>%
    group_by(game_id, season) %>%
    filter(
      sum(post_fight == 0) >= .env$min_before,
      sum(post_fight == 1) >= .env$min_after
    ) %>%
    ungroup() %>%
    mutate(y = 1L - RC)
  
  if (nrow(data) == 0) {
    stop("No rows left after filtering.")
  }
  
  # Save the exact sample shared across all model specifications
  estimation_sample <- data %>%
    transmute(
      season = as.character(season),
      game_id = as.character(game_id),
      IAT,
      post_fight,
      RC,
      intradivision
    )
  
  # Prevent specifications from silently using different samples
  if (any(is.na(data$season_month))) {
    stop(
      "season_month is NA for ",
      sum(is.na(data$season_month)),
      " rows. Refusing to proceed because the month specification would ",
      "use a different sample. Check game_date coverage in ",
      "build_all_IAT_tables()."
    )
  }
  
  if (sum(data$y) == 0) {
    stop("No observed violent-event intervals left after filtering.")
  }
  
  if (sum(data$IAT) <= 0) {
    stop("Total IAT exposure time is zero or negative.")
  }
  
  # 4. Record estimation-sample totals
  n_games <- n_distinct(data$cluster_id)
  n_iats <- nrow(data)
  
  n_pre <- sum(data$post_fight == 0)
  n_post <- sum(data$post_fight == 1)
  
  n_pre_observed <- sum(
    data$post_fight == 0 &
      data$RC == 0
  )
  
  n_post_observed <- sum(
    data$post_fight == 1 &
      data$RC == 0
  )
  
  n_pre_right_censored <- sum(
    data$post_fight == 0 &
      data$RC == 1
  )
  
  n_post_right_censored <- sum(
    data$post_fight == 1 &
      data$RC == 1
  )
  
  n_right_censored <- sum(data$RC == 1)
  
  if (n_games <= 1) {
    stop("Fewer than two game clusters; clustered inference is undefined.")
  }
  
  message(
    "Filtered data: ",
    n_games,
    " games and ",
    n_iats,
    " IAT rows."
  )
  
  # Store average post-fight effects generated by each model
  ate_results_env <- new.env(parent = emptyenv())
  ate_results_env$rows <- list()
  
  # Collector for the estimated game fixed effects, filled by fit_model()
  # for the game fixed-effects specification only.
  game_fe_env <- new.env(parent = emptyenv())
  game_fe_env$fe <- NULL
  
  # 5. Fit one model specification
  fit_model <- function(formula, model_name) {
    
    message("  Fitting model: ", model_name)
    
    # The Poisson representation maximizes the censored exponential
    # log-likelihood using y = 1 - RC and log(IAT) as the offset.
    fit <- feglm(
      formula,
      data = data,
      family = poisson(),
      offset = ~log(IAT)
    )
    
    beta_hat <- coef(fit)
    
    # Calculate game-clustered and model-based standard errors
    se_cluster <- se(
      fit,
      cluster = ~cluster_id
    )
    
    se_model_based <- se(
      fit,
      vcov = "iid"
    )
    
    z_hat <- beta_hat / se_cluster
    p_hat <- 2 * (1 - pnorm(abs(z_hat)))
    
    # Calculate the exponential log-likelihood on the paper's reported scale
    lambda_hat <- fitted(fit) / data$IAT
    
    exp_log_lik <- sum(
      data$y * log(lambda_hat)
    ) - sum(
      lambda_hat * data$IAT
    )
    
    convergence <- if (isTRUE(fit$convStatus)) {
      0L
    } else {
      1L
    }
    
    if (convergence != 0L) {
      warning("Model ", model_name, " did not converge cleanly.")
    }
    
    # Calculate counterfactual post-fight effects for every observation
    rhs_formula <- formula(
      fit,
      type = "linear"
    )
    
    rhs_formula <- as.formula(
      paste(
        "~",
        deparse1(rhs_formula[[3]])
      )
    )
    
    X1 <- model.matrix(
      rhs_formula,
      data = data %>%
        mutate(post_fight = 1L)
    )
    
    X0 <- model.matrix(
      rhs_formula,
      data = data %>%
        mutate(post_fight = 0L)
    )
    
    shared <- intersect(
      colnames(X1),
      names(beta_hat)
    )
    
    X1 <- X1[, shared, drop = FALSE]
    X0 <- X0[, shared, drop = FALSE]
    theta <- beta_hat[shared]
    
    # Shift each observed linear predictor to its pre- and post-fight values
    D <- X1 - X0
    shift <- as.vector(D %*% theta)
    
    lambda_0 <- exp(
      log(lambda_hat) -
        data$post_fight * shift
    )
    
    lambda_1 <- lambda_0 * exp(shift)
    
    # Average fitted rates, expressed as events per minute
    rate_pre <- mean(lambda_0) * 60
    rate_post <- mean(lambda_1) * 60
    rate_diff <- rate_post - rate_pre
    
    # Average the observation-level post-to-pre rate ratios
    ratio_i <- exp(shift)
    avg_ratio <- mean(ratio_i)
    
    vcov_cluster <- vcov(
      fit,
      cluster = ~cluster_id
    )[shared, shared, drop = FALSE]
    
    se_of <- function(g) {
      sqrt(
        as.numeric(
          t(g) %*% vcov_cluster %*% g
        )
      )
    }
    
    # Delta-method standard errors
    grad_ratio <- colMeans(D * ratio_i)
    ratio_se <- se_of(grad_ratio)
    
    grad_0 <- colMeans(X0 * lambda_0) * 60
    grad_1 <- colMeans(X1 * lambda_1) * 60
    diff_se <- se_of(grad_1 - grad_0)
    
    ratio_z <- (avg_ratio - 1) / ratio_se
    
    ate_row <- tibble(
      model = model_name,
      n_obs = nrow(X1),
      rate_pre = rate_pre,
      rate_post = rate_post,
      rate_difference = rate_diff,
      rate_difference_se = diff_se,
      avg_rate_ratio = avg_ratio,
      std_error = ratio_se,
      ci_lo = avg_ratio - 1.96 * ratio_se,
      ci_hi = avg_ratio + 1.96 * ratio_se,
      z_value = ratio_z,
      p_value = 2 * (1 - pnorm(abs(ratio_z))),
      se_type = "clustered_by_game"
    )
    
    ate_results_env$rows[[model_name]] <- ate_row
    
    # ---- Estimated game fixed effects (game FE specification only) --------
    # One intercept per game, each estimated from that game's own intervals.
    # Saved with the game-level covariates so the distribution can be
    # inspected and faceted. Note the level of the fixed effects is only
    # identified up to a normalization; the spread is what is meaningful.
    if (model_name == "game_fixed_effects") {
      
      fe_values <- fixef(fit)$cluster_id
      
      game_covariates <- data %>%
        group_by(cluster_id) %>%
        summarise(
          season = first(as.character(season)),
          game_id = first(as.character(game_id)),
          n_iats = n(),
          n_events = sum(y),
          total_exposure = sum(IAT),
          intradivision = first(intradivision),
          fight_period = first(fight_period),
          fight_score_diff_cat = first(fight_score_diff_cat),
          season_month = first(season_month),
          .groups = "drop"
        ) %>%
        mutate(cluster_id = as.character(cluster_id))
      
      game_fe_env$fe <- tibble(
        cluster_id = names(fe_values),
        game_fe = as.numeric(fe_values)
      ) %>%
        left_join(game_covariates, by = "cluster_id") %>%
        mutate(
          # exp(alpha) is the game's fitted rate in events per second for
          # the reference category; x60 puts it in events per minute.
          game_rate_per_min = exp(game_fe) * 60
        )
    }
    
    tibble(
      model = model_name,
      term = names(beta_hat),
      estimate = unname(beta_hat),
      std_error = unname(se_cluster),
      std_error_model_based = unname(se_model_based),
      z_value = unname(z_hat),
      p_value = unname(p_hat),
      rate_ratio = exp(unname(beta_hat)),
      log_lik = exp_log_lik,
      convergence = convergence,
      se_type = "clustered_by_game"
    )
  }
  
  # 6. Define the model ladder
  model_specs <- list(
    # Post-fight indicator and current-period fixed effects
    iat_period_controls =
      y ~ post_fight + current_period,
    
    # Add season fixed effects and intradivision status
    season_controls =
      y ~ post_fight + current_period + season + intradivision,
    
    # Add month fixed effects and score-differential interactions
    month_fixed_effects =
      y ~ post_fight + current_period + season + intradivision +
      season_month + post_fight * fight_score_diff_cat,
    
    # Add game fixed effects; game-level main effects are absorbed
    game_fixed_effects =
      y ~ post_fight + current_period +
      post_fight:fight_score_diff_cat | cluster_id
  )
  
  # 7. Estimate all model specifications
  coefficient_results <- imap_dfr(
    model_specs,
    ~fit_model(.x, .y)
  )
  
  ate_results <- bind_rows(
    ate_results_env$rows[names(model_specs)]
  )
  
  convergence_check <- coefficient_results %>%
    distinct(model, convergence)
  
  print(convergence_check)
  
  if (any(convergence_check$convergence != 0)) {
    warning("At least one model did not converge cleanly.")
  }
  
  if (any(is.na(coefficient_results$std_error))) {
    warning("At least one clustered standard error is NA.")
  }
  
  # 8. Construct the model-level summary
  model_summary <- coefficient_results %>%
    group_by(model) %>%
    summarise(
      log_lik = first(log_lik),
      convergence = first(convergence),
      se_type = first(se_type),
      first_season = first_season,
      last_season = last_season,
      season_range = season_folder_name,
      n_games = n_games,
      n_iats = n_iats,
      n_iats_pre_fight = n_pre,
      n_iats_post_fight = n_post,
      n_observed_pre_fight = n_pre_observed,
      n_observed_post_fight = n_post_observed,
      n_right_censored = n_right_censored,
      n_right_censored_pre_fight = n_pre_right_censored,
      n_right_censored_post_fight = n_post_right_censored,
      min_iat_rows_before = .env$min_before,
      min_iat_rows_after = .env$min_after,
      season_controls = first(model) %in% c(
        "season_controls",
        "month_fixed_effects"
      ),
      intradivision_control = first(model) %in% c(
        "season_controls",
        "month_fixed_effects"
      ),
      score_diff_controls = first(model) %in% c(
        "month_fixed_effects",
        "game_fixed_effects"
      ),
      score_diff_interaction = first(model) %in% c(
        "month_fixed_effects",
        "game_fixed_effects"
      ),
      period_interaction = FALSE,
      period_fixed_effects = TRUE,
      month_fixed_effects =
        first(model) == "month_fixed_effects",
      game_fixed_effects =
        first(model) == "game_fixed_effects",
      fight_period_controls = FALSE,
      .groups = "drop"
    )
  
  # 9. Save all model outputs
  output_folder <- file.path(
    working.dir,
    "generated",
    "fights",
    season_folder_name
  )
  
  dir.create(
    output_folder,
    recursive = TRUE,
    showWarnings = FALSE
  )
  
  coefficient_file <- file.path(
    output_folder,
    paste0(
      "IAT_regression_coefficients_",
      season_folder_name,
      ".rds"
    )
  )
  
  summary_file <- file.path(
    output_folder,
    paste0(
      "IAT_regression_model_summary_",
      season_folder_name,
      ".rds"
    )
  )
  
  ate_file <- file.path(
    output_folder,
    paste0(
      "IAT_regression_avg_rate_ratios_",
      season_folder_name,
      ".rds"
    )
  )
  
  game_fe_file <- file.path(
    output_folder,
    paste0(
      "IAT_game_fixed_effects_",
      season_folder_name,
      ".rds"
    )
  )
  
  sample_file <- file.path(
    output_folder,
    paste0(
      "IAT_estimation_sample_",
      season_folder_name,
      ".rds"
    )
  )
  
  saveRDS(coefficient_results, coefficient_file)
  saveRDS(model_summary, summary_file)
  saveRDS(ate_results, ate_file)
  saveRDS(estimation_sample, sample_file)
  
  if (!is.null(game_fe_env$fe)) {
    saveRDS(game_fe_env$fe, game_fe_file)
  }
  
  output_folder_full <- normalizePath(
    output_folder,
    winslash = "/",
    mustWork = TRUE
  )
  
  message(
    "Saved coefficient results to: ",
    normalizePath(
      coefficient_file,
      winslash = "/"
    )
  )
  
  message(
    "Saved model summary to: ",
    normalizePath(
      summary_file,
      winslash = "/"
    )
  )
  
  message("Finished season range: ", season_folder_name)
  
  list(
    season_range = season_folder_name,
    output_folder = output_folder_full,
    coefficient_file = normalizePath(
      coefficient_file,
      winslash = "/"
    ),
    summary_file = normalizePath(
      summary_file,
      winslash = "/"
    ),
    coefficients = coefficient_results,
    game_fixed_effects = game_fe_env$fe,
    avg_rate_ratios = ate_results,
    model_summary = model_summary
  )
}